background {
    monitor =
    path = /home/max/Downloads/Arch Linux Wallpaper 4K.png
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = rgb(1793d1)
    inner_color = rgb(1a1a2e)
    font_color = rgb(e0e0f0)
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(e0e0f0)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi, $USER
    color = rgb(1793d1)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 30
    halign = center
    valign = center
}
